name: ci
on:
  push:
    branches:
      - master
      - 2.7
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: ['9.0', '8.10', '8.8', '8.6', '8.4', '8.2']
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - uses: actions/cache@v2.1.6
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Build
      run: |
        autoreconf -i
        cabal sdist -z -o .
        cabal get unix-*.tar.gz
        cd unix-*/
        cabal update
        cabal test all --test-show-details=direct
    - name: Haddock
      run: cabal haddock

  build-freebsd:
    needs: build
    # See https://github.com/vmactions/freebsd-vm#under-the-hood.
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      id: build-freebsd
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        prepare: pkg install -y ghc hs-cabal-install git autoconf
        run: |
          autoreconf -i
          cabal sdist -z -o .
          cabal get unix-*.tar.gz
          cd unix-*/
          cabal update
          cabal test all --test-show-details=direct
